version: '3'
services:
  minecraft-mod:
    user: "minecraft"
    build:
      context: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/minecraft/.Xauthority
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/minecraft/.Xauthority
      - EULA=true
    command: ./gradlew runClient --scan
